### PR TITLE
(WIP) New intra predictors

### PR DESCRIPTION
**Pull request by hohMiyazawa**
Tested some promising simple intra predictors, since I didn't understand why they were not in the existing image model.
Here are the five that gave the most significant gains, and rather curiously that includes the 0 predictor.

Tested on a test set of 40 photographic + 40 synthetic images
```
significance: 6.35 sigma
size reduction: 1.89e-4
normalized size reduction: 2.15e-4
```

TODO:
- Independent verification on other test sets. (failed)
- Get reliable timings (if slowdown is linear with the number of intra predictors, a ~5% increase in coding time is expected).
- Test more predictors
- Even if statistically significant, is this reasonable for the time/size tradeoff? (failed)
- Formal contribution requirements.

### CODE REVIEW

**Comment by GotthardtZ** [comment]
Oh, hello hohMiyazawa,

Nice to see you back again!

I had a look at the changes and tested the three new contexts with some of my (mostly) photographic test files (from darek, maximumcompression, lpcb ans some independent ones).
My first note is about the "0" predictor. As it is used in "mapContexts" which needs a *predicted* value (what the next byte would be), you are predicting the next byte would be a constant 0. This is suspicious. Did you test this predictor alone? I've just did, and it doesn't seem to add any value to compression according to my tests (at least to photographic images).

The other two predictors have a very tiny gain for some files but some other files in my tests got a tiny loss.
Some of the results:

```
Level: 9
10'605'652 canon_eos_1100d_13.ppm.paq8px206
10'605'737 canon_eos_1100d_13.ppm.paq8px207
 7'567'694 fujifilm_finepix_x100_06.ppm.paq8px206
 7'567'455 fujifilm_finepix_x100_06.ppm.paq8px207
11'151'955 olympus_xz1_14.ppm.paq8px206
11'152'054 olympus_xz1_14.ppm.paq8px207
 1'775'647 STA13458.ppm.paq8px206
 1'775'716 STA13458.ppm.paq8px207
 1'871'049 sony_a55_11.ppm.paq8px206
 1'871'028 sony_a55_11.ppm.paq8px207

Level: 8
2'223'573 STA13843.ppm.paq8px206
2'223'461 STA13843.ppm.paq8px207
  464'857 rafale.bmp.paq8px206
  464'854 rafale.bmp.paq8px207
  208'986 1.bmp.paq8px206
  208'972 1.bmp.paq8px207
  330'361 B.TGA.paq8px206
  330'363 B.TGA.paq8px207
  357'915 A.TIF.paq8px206
  357'917 A.TIF.paq8px207
   78'352 dog.pnm.paq8px206
   78'266 dog.pnm.paq8px207
```

So yes, your gut is probably right: the advantage they seem to bring is too tiny if any.

>>Even if statistically significant, is this reasonable for the time/size tradeoff?
In order to train your intuition you could remove some existing contexts one at a time to find how much effect they had on the result (compressed size). There are some very strong predictors and naturally some weaker ones as well. Then you'll know how much tradeoff was taken so far. This way you'll know the "fitness" of your own new predictors.

From my experience of trying adding and changing contexts in the 24-bit image model, I have the feeling that using the "tight" neighboring pixels are already very well covered with contexts in paq8px. Probably we'll need new tricks (such as smoothing for more noisy images) or to reach farther in the neighborhood to get more gain.

If you have further ideas, or would like to show some results, you can pop in the forum (https://encode.su/threads/342-paq8px).

**Comment by hohMiyazawa** [comment]
Thank you for testing!

Yes, always predicting 0 is very suspicious. But since it passed the methodology I had set up, disregarding it when it passed would be the wrong way to apply statistics.
(it was compression neutral for photographic, nearly all gains was for synthetic images)

This all probably shows that my test sets contains too much bias in one way or another to be suitable for tuning the image model.

**Comment by hohMiyazawa** [comment]
What could perhaps have gone wrong here:
I did my tests on memory level ``-3``, figuring the hash space shouldn't have (too) strong implications for the relative fitness between predictors. This also helps with running tests in parallel.
Is this flawed methodology?

**Comment by GotthardtZ** [comment]
>>it was compression neutral for photographic, nearly all gains was for synthetic images)

Yes, that's expected. Very well observed.

>>I did my tests on memory level -3

Ah, aha!
Try testing at level 8 or above. (For small images it doesn't worth to go higher than that, for larger images - it's a must.)

As paq8px is sacrificing memory and speed for compression ratio, it's used with high memory settings almost by everyone in all cases -> a low setting is not really used in practice.

>>figuring the hash space shouldn't have (too) strong implications for the relative fitness between predictors. 

The lower the memory level is the more adaptive these models or contexts using hash tables will be. They will tend to strongly favor new statistics and forget old statistics faster. Thus, on lower levels the longer-order statistics cannot be learned - they are evicted faster from the hash tables.
Any other contexts (that are not using a hash table) are unaffected by the memory level - thus they perform the same on low or high settings. This means that the relative performance is affected: on low levels the hash table models/contexts are (such as the "cm" contexts) in disadvantage vs the others not using hash tables (such as the "mapContexts" contexts)). 
Also note that the compression level affects the performance of NormalModel and MatchModel (this latter two are also turned on for images). Changing the memory level has an effect on their behavior (adaptivity). These two models are essential for synthetic images.

>>(original source of optimism attached)

Aha - if there are gains for almost all files, that's a very good sign!
I'm curious what we would see if you go to a higher memory level (8+).

**Comment by hohMiyazawa** [comment]
[optimism2.ods](https://github.com/hxim/paq8px/files/8499462/optimism2.ods)


Re-ran my test set at level ``-9`` overnight.

**Comment by hohMiyazawa** [comment]
Until a better idea shows up, I might as well continue to try investigating why these tight predictors are beneficial one some types of test data but not others.

**Comment by hohMiyazawa** [comment]
Signed up for encode.su if that's more appropriate for discussion.

**Pull request closed without merging**
