### PR TITLE
v184 - Large refactoring

### PR DESCRIPTION
**Pull request by andrew-epstein**

### CODE REVIEW

**Comment by hxim** [comment]
I tried to compile it on windows with MinGW-W64 GCC-8.1.0, MSYS 1.0.11 and cmake-3.16.2.
And found 4 problems in source code:
1.) in fileUtils.hpp there is `#include <cerrno>` missing (ENOENT not found)
2.) in OpenFromMyFolder.cpp `myPathError` should be `ofmf::myPathError`
3.) in OpenFromMyFolder.cpp `endofpath `should be `EndOfPath`
4.) in OpenFromMyFolder.hpp i deleted `#include <mach-o/dyld.h>` I don't have such file and it is not needed on windows I guess?
After fixing those and modification of section `CMakeLists.txt` like this
```
set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_FLAGS "-std=gnu++1z -static -O3 -march=native -mtune=native -fno-stack-protector")
set(CMAKE_AR "gcc-ar")
add_definitions(-DUSE_TEXTMODEL -DUSE_AUDIOMODEL -DUSE_ZLIB -DNVERBOSE -DNDEBUG -DWINDOWS)
```
I was able to compile successfully with these command line commands
```
mkdir build
cd build
cmake -G "MSYS Makefiles" -DCMAKE_C_COMPILER="c:/mingw/mingw64/bin/gcc.exe" -DCMAKE_CXX_COMPILER="c:/mingw/mingw64/bin/g++.exe" -DZLIB_INCLUDE_DIR=c:/mingw/zlib-1.2.11 -DZLIB_LIBRARY=c:/mingw/zlib-1.2.11/build/libzlibstatic.a ..
mingw32-make
 ``` 
Not sure if this is correct way to do it I don't usually use those compile tools.
Please let me know after you finish your refactoring and v184 is finished and I will merge this pull request.

**Comment by andrew-epstein** [comment]
@hxim Thank you very much for the report. I have fixed the 4 source code problems you found. (`<mach-o/dyld.h>` is only required on macOS, FYI).

I still have more refactoring to do, so I'll ask that this PR is left open for now. I'll post again when it's ready to be merged.

**Comment by hxim** [comment]
> 
> 
> @hxim Thank you very much for the report. I have fixed the 4 source code problems you found. (`<mach-o/dyld.h>` is only required on macOS, FYI).
> 
> I still have more refactoring to do, so I'll ask that this PR is left open for now. I'll post again when it's ready to be merged.

Ok, great.

**Comment by andrew-epstein** [comment]
@hxim I think it's time to merge this. Thanks for your patience. Would you test the compilation on Windows for me?

**Comment by hxim** [comment]
I checked compilation still works, only I needed to remove  `3rd/cxxopts.cpp` from CMakeLists.txt this line: 
https://github.com/andrew-epstein/paq8px/blob/e9a7961ced953092dc1f31d8e59039312e242b04/CMakeLists.txt#L13
which causes paq8px.exe to not work and be 3 times bigger for some reason...
and used same parameters as before
```
set(CMAKE_CXX_FLAGS "-std=gnu++1z -static -O3 -march=native -mtune=native -fno-stack-protector")
set(CMAKE_AR "gcc-ar")
add_definitions(-DUSE_TEXTMODEL -DUSE_AUDIOMODEL -DUSE_ZLIB -DNVERBOSE -DNDEBUG -DWINDOWS)
```
Also checked compression and decompression with my exe works.
When I tested I noticed A10.jpg is compressed with v183 and version from 12 January to identical file (628388 bytes) but today's version it compressed to 628380 file is this expected result?

**Comment by andrew-epstein** [comment]
I updated `CMakeLists.txt` with the change to remove `3rd/cxxopts.cpp`. If you don't make any other changes to `CMakeLists.txt`, does compilation fail for you? If so, what error messages do you get?

I do not know why A10.jpg would compress slightly smaller. My best guess is that one of the changes I made affected some edge case -- perhaps involving formerly undefined behavior. As long as it decompresses correctly, I'm not concerned.

**Comment by hxim** [comment]
@andrew-epstein 
Now I am getting errors like this. Do you know what I am doing wrong?
scr1

**Comment by andrew-epstein** [comment]
Sorry, that's my fault. `clang-tidy` sometimes tries to apply multiple fixes to one line and breaks the code. I just pushed some commits that should allow you to compile.

**Comment by hxim** [comment]
@andrew-epstein 
OK. Now if I don't make any other changes to CMakeLists.txt compilation works.
Just FYI I see this warnings:
obrazek
and those
obrazek
And when running exe it says this because it is not static:
obrazek
But if I add those dll to paq8px.exe location or modify CMakeLists,txt it works with no issues.
So I am merging this now...

**Pull request merged**
