### PR TITLE
add avx512 neural network functions

### PR DESCRIPTION
**Pull request by ahorek**

### CODE REVIEW

**Comment by GotthardtZ** [comment]
This PR alone can't be merged, as this includes only the detection part (as you also commented).
With these changes alone paq8px reports "Using AVX512 neural network functions." which would be deceiving as it's not true. Also it doesn't compile with VC++.

Created a PR to your branch: added those avx512 functions and fixed the build issue with VC++. 

```
enwik6 runtimes (sec) at level 8 on an Intel Core i7-1165G7
       +--------+--------+--------+--------+
       |Round 1 |Round 2 |Round 3 |Round 4 |
       +--------+--------+--------+--------+
none   |      * | 357.53 | 359.62 | 358.72 |
sse2   | 126.62 | 126.05 | 126.27 | 125.84 |
avx2   | 113.53 | 112.98 | 113.38 | 112.83 |
avx512 | 111.19 | 112.00 | 112.48 | 112.20 |
-------+--------+--------+--------+--------+
* = warmup run
```

**Comment by ahorek** [comment]
that's great, thank you for finishing it!

my results on Ryzen 7950x
```
       +--------+--------+--------+--------+
       |enwiki6 |speedup |
       +--------+--------+--------+--------+
none   | 329.96 | 1.00x | 
sse2   | 77.61  | 4.25x | 
avx2   | 68.80  | 4.80x | 
avx512 | 68.03  | 4.85x | 
-------+--------+--------+--------+--------+

       +--------+--------+--------+--------+
       |txt |speedup |
       +--------+--------+--------+--------+
none   | 272.37 | 1.00x |
sse2   | 64.39  | 4.23x |
avx2   | 59.54  | 4.57x |
avx512 | 56.55  | 4.82x |
-------+--------+--------+--------+--------+

       +--------+--------+--------+--------+
       |exe |speedup |
       +--------+--------+--------+--------+
none   | 574.51 | 1.00x | 
sse2   | 117.47 | 4.89x | 
avx2   | 100.51 | 5.72x | 
avx512 | 98.44  | 5.84x | 
-------+--------+--------+--------+--------+

       +--------+--------+--------+--------+
       |bmp |speedup |
       +--------+--------+--------+--------+
none   | 306.82 | 1.00x | 
sse2   | 83.29  | 3.68x | 
avx2   | 74.83  | 4.10x | 
avx512 | 74.73  | 4.11x | 
-------+--------+--------+--------+--------+

       +--------+--------+--------+--------+
       |ltsm |speedup |
       +--------+--------+--------+--------+
none   | 70.98 | 1.00x | 
sse2   | 39.82 | 1.78x | 
avx2   | 23.53 | 3.02x | 
avx512 | 23.31 | 3.05x | 
-------+--------+--------+--------+--------+
```

**Comment by GotthardtZ** [comment]
@hxim 
This PR may be merged.

**Comment by hxim** [comment]
> @hxim This PR may be merged.

Ok.

**Pull request merged**
